on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string
      cache-path:
        required: true
        type: string
      valid-cache:
        required: true
        type: boolean
      os:
        required: true
        type: string
      arch:
        required: false
        type: string
      build-deps-only:
        required: false
        type: boolean
      force-build:
        required: false
        type: boolean

jobs:
  build_deps:
    name: Build Deps
    if: ${{ !cancelled() && (inputs.build-deps-only || inputs.force-build || inputs.valid-cache != true) }}
    runs-on: ${{ inputs.os }}
    env:
      date:
    steps:

      # Setup the environment
      - name: Checkout
        uses: actions/checkout@v7
        with:
          lfs: 'false'

      - name: load cached deps
        uses: actions/cache@v6
        with:
          path: ${{ inputs.cache-path }}
          key: ${{ inputs.cache-key }}

      - name: Build deps
        uses: ./.github/actions/build-deps
        with:
          arch: ${{ inputs.arch }}
          self-hosted: ${{ vars.SELF_HOSTED }}


      # Upload Artifacts
      # - name: Upload Mac ${{ inputs.arch }} artifacts
      #   if: runner.os == 'macOS'
      #   uses: actions/upload-artifact@v6
      #   with:
      #     name: OrcaSlicer_dep_mac_${{ env.date }}
      #     path: ${{ github.workspace }}/deps/build/OrcaSlicer_dep*.tar.gz

      # - name: Upload Windows artifacts
      #   if: runner.os == 'Windows'
      #   uses: actions/upload-artifact@v6
      #   with:
      #     name: OrcaSlicer_dep_win64_${{ env.date }}
      #     path: ${{ github.workspace }}/deps/build/OrcaSlicer_dep*.zip

      # - name: Upload Ubuntu artifacts
      #   if: runner.os == 'Linux' && !env.ACT
      #   env:
      #     ubuntu-ver: '2404'
      #   uses: actions/upload-artifact@v6
      #   with:
      #     name: OrcaSlicer_dep_ubuntu_${{ env.ubuntu-ver }}_${{ env.date }}
      #     path: ${{ github.workspace }}/deps/build/OrcaSlicer_dep_ubuntu_*.tar.gz

  build_orca:
    name: Build OrcaSlicer
    needs: [build_deps]
    if: ${{ !cancelled() && !inputs.build-deps-only && (inputs.force-build || (inputs.valid-cache == true && needs.build_deps.result == 'skipped') || (inputs.valid-cache != true && success())) }}
    uses: ./.github/workflows/build_orca.yml
    with:
      cache-key: ${{ inputs.cache-key }}
      cache-path: ${{ inputs.cache-path }}
      os: ${{ inputs.os }}
      arch: ${{ inputs.arch }}
    secrets: inherit
